### PR TITLE
Feat/blog search

### LINKED ISSUE #93: Implement Search Dropdown
Description:

Reporter:
James Elgar 

Trello link:
https://trello.com/c/0mIvQzrR/222-implement-search-dropdown

Comments:

### PR DESCRIPTION
**Pull request by shah-tejas**
# Description

Implements Search feature for the blogs. Allows to filter blogs based on selected campaigns.

Trello Link: [Implement Search Dropdown](https://trello.com/c/0mIvQzrR/222-implement-search-dropdown)
Fixes #93 

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have reviewed the 'files changed' tab on github to ensure all changes are expected
- [x] I have added someone to review the pr

### CODE REVIEW

**Review by JElgar — CHANGES_REQUESTED** [review]
When I open the dropdown It just seems to show an empty small white square

**Comment by shah-tejas** [comment]
> When I open the dropdown It just seems to show an empty small white square

Yes, that is due to the campaigns url not fetching the respective campaigns, for which blogs exist.

**Comment by JElgar** [comment]
ah 🤣

**Comment by shah-tejas** [comment]
@JElgar Fixed it now. Fetching old campaings, and appending them to the new campaigns. Dropdown works fine now.

**Comment by JElgar** [comment]
Screenshot 2020-08-29 at 08 44 55

I just spotted this but I don't know if that's related to this pr? And similarly, on the right-hand side it says "This month campaign" opposed to "this month's campaigns" and then show all the campaigns instead of just this months. 

Also this seems to happen on smaller screens 
Screenshot 2020-08-29 at 08 58 29

**Review by JElgar — CHANGES_REQUESTED** [review]
Left a few comments which may or may not be related to this pr. The actual search feature looks great though!

**Comment by stellenberger** [comment]
Thank you for this - looks great! 

Regarding the blog dropdown menu, is there a scroll feature added to this? 

At the moment if I untick all the available choices, there are still some blogs showing, which makes me think that some of the checkboxes are hidden from view (plus bottom checkbox is cut a little shorter)? 

Screenshot 2020-09-02 at 08 48 05

**Comment by shah-tejas** [comment]
Hi @JElgar & @stellenberger,

Apologies for the delay in addressing the review comments! I have addressed the following -
- This Month's Campaigns now shows only this month's campaigns
- Fixed the typo with "This Month's Campaign"
- Center aligned the App Download div
- Added the vertical scroll bar on the SearchDropdown on overflow

Thank you for catching these, I had missed them and hopefully these should now be fixed!

**Pull request merged**
