### PR TITLE
Blog fixes

### LINKED ISSUE #24: Blog

### PR DESCRIPTION
**Pull request by JElgar**
# Description

I just thought I'd make a branch in the main repo so everyone can get involved. I've fixed a few things I've spotted, Ill check through the comments on the last pr and see what else we can get done before release.

Fixes #24 

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have reviewed the 'files changed' tab on github to ensure all changes are expected
- [ ] I have added someone to review the pr

### CODE REVIEW

**Comment by tunangst** [comment]
Pardon me, but I don't seem to understand how this is supposed to work.
I first thought it was going to be like an open branch anyone could add stuff to, but I can only seem to find a weird way of contributing.

- clone branch
- make the change on a local branch
- pull request into upstream's fix/blog_fixes branch

Unless now-u/campaign's fix/blog_fixes branch is going to get constantly merged, I don't understand how multiple people can contribute.
sorry, learning :^]

**Comment by JElgar** [comment]
Hello @tunangst. Hmm, this sounds strange, in theory, this branch is on the repo so you should (if you have this repo cloned) just be able to fetch and then checkout to this branch. From there you can just push changes to the branch. If a lot of people are working on this branch you could also branch off this branch and then merge your fixes into this branch later.

**Comment by stellenberger** [comment]
Here are some instructions in order to work on this branch - 

Clone this repo using 
`$ git clone git@github.com:now-u/now-u-campaigns.git`

Pull the latest changes from inside the repo folder 
`$ git pull`

Check out to the branch that this Pull Request is located on 
`$ git checkout remotes/origin/fix/blog_fixes`

Make some changes, have some coffee, and commit your changes and push :)

**Comment by tunangst** [comment]
> 
> 
> Here are some instructions in order to work on this branch -
> 
> Clone this repo using
> `$ git clone git@github.com:now-u/now-u-campaigns.git`
> 
> Pull the latest changes from inside the repo folder
> `$ git pull`
> 
> Check out to the branch that this Pull Request is located on
> `$ git checkout remotes/origin/fix/blog_fixes`
> 
> Make some changes, have some coffee, and commit your changes and push :)

Thank you, I was trying in my forked repo 🗡️ 🍴

**Comment by tunangst** [comment]
I don't think design has yet created a mockup for us yet, but I wouldn't mind adding some semantic html if you guys don't mind.

**Comment by JElgar** [comment]
I think this is an issue that may already be in the blog:
https://github.com/now-u/now-u-campaigns/pull/92#issuecomment-683253732
So if anyone fancies fixing that ❤️

**Comment by JElgar** [comment]
> I don't think design has yet created a mockup for us yet, but I wouldn't mind adding some semantic html if you guys don't mind.

I don't mind but what is semantic html? Does it have any cross over with the markdown package that we are using?

**Comment by tunangst** [comment]
>  don't mind but what is semantic html? Does it have any cross over with the markdown package that we are using?

Well, it makes the markup easier to read for devs as well as devices like screen readers and search engine crawling. It will help with the div spam also.
The ones I use the most really are <header><footer><section><main><aside><figure><figcaption>
I have not run into any issues of browsers or compilers rejecting them. I figure if they did get rejected, it may default to a div, not sure.

**Comment by JElgar** [comment]
I'm going to merge these in but not close the branch so please do keep working on the blog from here!

**Pull request merged**
